- title: Administración de Servicios
- p: Permite al usuario administrar sus servicios, unificándolos en una sola plataforma. Además de poder consultar información de los servicios agregados, el usuario será notificado de sus adeudos próximos a vencerse, funcionando como una excelente herramienta para garantizar el pago puntual.

- title2: Créditos
- p2: Garantiza la rapidez en solicitud y otorgamiento de créditos, ya que permite al usuario realizar una solicitud de crédito en menos de 10 minutos, así como el seguimiento del mismo una vez aprobado. La doble validación permitirá corroborar la autenticidad de los datos del aplicante.

- title3: Ahorro
- p3: La herramienta ideal para cumplir con objetivos financieros a corto y largo plazo. El usuario podrá ver su avance durante todo proceso, desde el momento de la configuración hasta el cumplimiento de su meta

- title4: Envío de dinero
- p4: Garantiza la rapidez en solicitud y otorgamiento de créditos, ya que permite al usuario realizar una solicitud de crédito en menos de 10 minutos, así como el seguimiento del mismo una vez aprobado.
